channels:
- conda-forge
dependencies:
- python=3.12.7
- pip<=24.2.1
- pip:
  - dagshub>=0.5.1
  - cloudpickle>=3.1.0
  - psutil>=5.9.0
  - scipy>=1.14.1
  - pandas>=2.0.0
  - numpy>=1.24.0
  - scikit-learn>=1.3.0
  - imbalanced-learn>=0.11.0
  - mlflow>=2.8.0
  - matplotlib>=3.7.0
  - seaborn>=0.12.0
name: mlflow-env

