name: MLflow Retrain

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CSV_URL: "loan_data_preprocessed.csv"

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.12.7
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.7"
      - name: Check Env
        run: |
          echo $CSV_URL
      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: mlflow-env
          environment-file: MLProject/conda.yaml
          auto-activate-base: false
      - name: Run mlflow project
        run: |
          source ~/.bashrc
          conda activate mlflow-env
          mlflow run MLProject --env-manager=local -P dataset=$CSV_URL
      - name: Save mlruns to repo
        run: |
          git config --global user.name ${{ secrets.USERNAME }}
          git config --global user.email ${{ secrets.EMAIL }}
          git add mlruns/
          git diff --cached --quiet || git commit -m "Save mlruns from CI run"
          git push origin main
      - name: Upload model artifact
        uses: actions/upload-artifact@v4
        with:
          name: trained-model
          path: MLProject/model_artifacts/
